/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HGUI;

import House.Model.atrr;
import HouseDB.HouseDao;
import com.sun.glass.events.KeyEvent;
import com.sun.webkit.event.WCKeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GRACE
 */
public class ROOMS extends javax.swing.JFrame {

    /**
     * Creates new form ROOMS
     */
    
    public ROOMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Rinput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Winput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Hinput = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Finput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 102));
        setForeground(new java.awt.Color(102, 255, 0));

        jLabel1.setText("Room No");

        Rinput.setText(" ");
        Rinput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RinputKeyPressed(evt);
            }
        });

        jLabel2.setText("width ");

        Winput.setText(" ");

        jLabel3.setText("height ");

        Hinput.setText(" ");
        Hinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinputActionPerformed(evt);
            }
        });

        btnadd.setText("Add Room");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jLabel4.setText(" Floor");

        Finput.setText(" ");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Finput, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hinput, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Rinput, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(Winput))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnadd)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Rinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Finput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Winput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Hinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HinputActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        
        String RoomNo=Rinput.getText();
        String Floor=Finput.getText();
        String Weight=Winput.getText();
        String Height=Hinput.getText();
        checkLength(Height);
        if(checkLength(Height)){
          JOptionPane.showMessageDialog(this, msg);  
        } else{
        atrr a =new atrr();
        
        a.setRoomNo(RoomNo);
        a.setFloor(Floor);
        a.setWidth(Weight);
        a.setLength(Height);
        
        HouseDao db=new HouseDao();
        db.SaveRoom(a);
        JOptionPane.showMessageDialog(this, a+"ROOM INSERTED");
                
        display();
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void RinputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RinputKeyPressed
        // TODO add your handling code here:
        int size = Rinput.getText().length();
        char a=evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        
          if(size>3){
          Rinput.setEditable(false);
          }else{
           Rinput.setEditable(true);
          }
          } else{
           if(evt.getExtendedKeyCode()==(evt.VK_BACK_SPACE)){
               Rinput.setEditable(true);
           }
           
        }
    }//GEN-LAST:event_RinputKeyPressed
 
    public void display(){
    
    HouseDao da=new HouseDao(); 
         List<atrr> ls=new ArrayList<>();
         ls =da.DisplayRoom();
        
        DefaultTableModel model=new DefaultTableModel();
        Object cols[]=new Object[5];
         cols[0]="RoomNo";
         cols[1]="Floor";
         cols[2]="Weight";
         cols[3]="Height";
         cols[4]="Size";
         
         model.setColumnIdentifiers(cols);
         
         
         for(atrr a:ls){
         
         Object rows[]=new Object[5];
         rows[0]=a.getRoomNo();
         rows[1]=a.getFloor();
         rows[2]=a.getWidth();
         rows[3]=a.getLength();
         rows[4]=getSize(a.getWidth(), a.getLength());
         model.addRow(rows);
          
         }
         Table.setModel(model);
    
    
    
    }
    
    public boolean checkLength(String h){
      double val;
      boolean err=false;
      try{
          val=Double.parseDouble(h);
          if(val>10){
              err=true;
          msg="Must be in range of 0 and 10";
          }
          
      }catch(Exception ex){
       msg="enter valid input of height..";
       err=true;
      }
     
      return err;
    }
    
    public double getSize(String a, String b){
     double size = Double.parseDouble(a)*Double.parseDouble(b);
     
     return size;
    }
    
    /**
     * @param args the command line arguments
     */
    String msg="";
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ROOMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ROOMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ROOMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ROOMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ROOMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Finput;
    private javax.swing.JTextField Hinput;
    private javax.swing.JTextField Rinput;
    private javax.swing.JTable Table;
    private javax.swing.JTextField Winput;
    private javax.swing.JButton btnadd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
